### PR TITLE
Update info.html

### PR DESCRIPTION
**Pull request by Fjtg**
## Proposed changes
Change the label name of info bar

This pull request addresses the issue with the "Last author" label on the component's Information tab by renaming it to "Last change made by". This change clarifies the information displayed, accurately reflecting that the label indicates the user responsible for the latest operation on the translation, including changes from the repository. This modification enhances clarity and aligns the label with the actual behavior of the feature, as discussed in issue 

## Checklist

- [ ] Lint and unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added documentation to describe my feature.
- [ ] I have squashed my commits into logic units.
- [x] I have described the changes in the commit messages.

## Other information

Issue Background
The issue originates from the "Last author" entry displayed on a component's Information tab in Weblate. Currently, this label is intended to show the name of the user who made the most recent modification to a translation. However, when Weblate automatically commits translations, the "Last author" field shows as "None", which does not provide any useful information to users. This inconsistency was noted because, in cases where users manually edit translations, their names appear correctly, while automatic updates from the repository leave the field empty.

My Thought Process
Upon reviewing the issue, I understood that the existing label could be misleading. Users might assume that the "Last author" should always display a meaningful name, regardless of whether the change came from a user or was automatically synced from the repository. This inconsistency could cause confusion and reduce the utility of the information displayed on the Information tab. To improve clarity, I decided to propose a change that accurately reflects the nature of the last modification, regardless of its source.

Modification Details
I modified the label from "Last author" to "Last change made by". This change clarifies that the field indicates the user or process responsible for the latest operation on the translation, which may include manual user edits or automatic commits from the repository. This new label provides more accurate and consistent information, eliminating confusion when the field shows "None" for automatic updates. The change was applied in both the template and backend code to ensure the label is updated across all relevant areas of the Weblate interface.

Future Plans
Testing: The next step is to thoroughly test this modification to ensure it behaves as expected. I plan to write and run both unit and integration tests to verify that the new label is displayed consistently, and that the information provided is correct for both manual edits and automatic updates. This will involve checking various scenarios, such as manual translations, bulk updates, and repository changes, to confirm the label’s accuracy.

Documentation Update: Alongside testing, I will update the documentation to reflect this change. The purpose is to make sure that users and contributors understand the new behavior of the "Last change made by" label, and know that it may refer to either a user or an automated process.

Merging the Changes: Once testing is complete and the changes are verified, I will proceed to merge this modification into the main repository. I plan to ensure that this update is included in the upcoming Weblate release (5.9 milestone). Before merging, I will also seek code reviews from other maintainers and contributors to gather feedback and make any necessary refinements.

Continuous Improvement: In the long term, I aim to explore the possibility of implementing a mechanism that tracks and displays the user responsible for changes made directly from the repository, if technically feasible. This would provide even more precise and informative data for users regarding translation modifications.

### CODE REVIEW

**Review by IrisZzzzZzz — COMMENTED** [review]
It looks like the issue referenced in your PR description might be incorrect, I think it should be 12696 instead. Or since this is a forked PR, we might not need to reference any issue for now, and you can also consider removing it from the description

**Comment by Fjtg** [comment]
> It looks like the issue referenced in your PR description might be incorrect, I think it should be 12696 instead. Or since this is a forked PR, we might not need to reference any issue for now, and you can also consider removing it from the description

Thank you, I suppose we should not reference issue for now.

**Review by YukeHuang123 — COMMENTED** [review]
all good

**Comment by nijel** [comment]
I've resubmitted this as https://github.com/WeblateOrg/weblate/pull/12862 against upstream repository.

**Comment by IrisZzzzZzz** [comment]
> I've resubmitted this as https://github.com/WeblateOrg/weblate/pull/12862 against upstream repository.

Thank you very much for your help! This is our first time contributing, and we originally intended to ensure everything worked on our fork before opening a PR upstream.

**Pull request merged**
